Add [ICommand] CanExecute property
CommunityToolkit/dotnet pull request #50
Opened 2021-12-03 13:25 UTC by Sergio0694

**Contributes to #8**

This PR adds the `CanExecute` property to `[ICommand]`.

### API breakdown:

```diff
 namespace CommunityToolkit.Mvvm.Input
 {
     public sealed class ICommandAttribute : Attribute
     {
+        public string? CanExecute { get; set; }
     }
 }
```

2021-12-04 01:08 UTC, XAML-Knight approved these changes

2021-12-04 01:46 UTC, Arlodotexe requested changes

2021-12-04 01:46 UTC, Arlodotexe commented on CommunityToolkit.Mvvm.SourceGenerators/Input/ICommandGenerator.cs
> +    /// <param name="canExecuteExpression">The resulting can execute expression, if available</param>
Missing period

2021-12-09 09:50 UTC, Sergio0694 commented on CommunityToolkit.Mvvm.SourceGenerators/Input/ICommandGenerator.cs
> +    /// <param name="canExecuteExpression">The resulting can execute expression, if available</param>
Fixed, thanks! 👍

2021-12-09 19:50 UTC, Arlodotexe approved these changes

2021-12-09 20:00 UTC, merged